# Generated by Django 5.1.1 on 2024-09-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('properties', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.companies')),
            ],
        ),
    ]
