# Generated by Django 5.1.1 on 2024-09-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_rawdatasets_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.companies')),
            ],
        ),
    ]
