# Generated by Django 5.1.5 on 2025-03-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_dataset_language_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=10)),
                ("error_message", models.TextField(blank=True)),
                (
                    "data_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_statuses",
                        to="catalog.dataset",
                    ),
                ),
                (
                    "document_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_statuses",
                        to="catalog.documentsource",
                    ),
                ),
                (
                    "product_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_statuses",
                        to="catalog.productsource",
                    ),
                ),
            ],
            options={
                "db_table_comment": "Tracks the synchronization status of plugins for datasets.",
            },
        ),
    ]
