# Generated by Django 5.1.1 on 2024-09-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_embeddingmodels_contentembeddings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentembeddings',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contentembeddings',
            old_name='model_code',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='contents',
            old_name='company_code',
            new_name='company',
        ),
    ]
