# Generated by Django 5.1.1 on 2024-10-03 09:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_embeddingdimensions_embeddingmodels_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawdatasets',
            name='categories',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='rawdatasets',
            name='properties',
            field=models.CharField(max_length=65535),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.embeddingmodels')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_at', models.DateTimeField()),
                ('question', models.TextField()),
                ('question_embedding', pgvector.django.vector.VectorField()),
                ('answer', models.TextField()),
                ('answer_embedding', pgvector.django.vector.VectorField()),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.conversation')),
            ],
        ),
    ]
