# Generated by Django 5.2.4 on 2025-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_rename_productchunk_productcontentchunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="properties",
            field=models.CharField(blank=True, max_length=65535),
        ),
    ]
