# Generated by Django 5.1.1 on 2024-10-07 09:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_document_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='dimensions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='system_name',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding', to='catalog.document'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_embedding',
            field=pgvector.django.vector.VectorField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='catalog.conversation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_embedding',
            field=pgvector.django.vector.VectorField(null=True),
        ),
    ]
