# Generated by Django 5.1.1 on 2024-10-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_conversation_dimensions_conversation_system_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='catalog.embeddingmodel'),
        ),
        migrations.CreateModel(
            name='AnswerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=1024)),
                ('cosine_distance', models.FloatField(null=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_document', to='catalog.conversation')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_document', to='catalog.document')),
                ('document_embedding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_document', to='catalog.documentembedding')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_document', to='catalog.question')),
            ],
            options={
                'db_table': 'ecl_answer_document',
                'db_table_comment': 'Document considered by our similarity search engine as similar to the question. Documents from this table were used to formulate the answer',
            },
        ),
    ]
