# Generated by Django 5.2.4 on 2025-10-31 12:00
import json

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_properties_to_json(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.all():
        if not product.categories_deprecated:
            product.properties = {}
        else:
            try:
                properties_dict = json.loads(product.properties_deprecated)
                product.properties = properties_dict
            except Exception:
                try:
                    properties_dict = {}
                    for property in product.properties_deprecated.split(";"):
                        key, value = property.split("->")
                        properties_dict[key.strip()] = value.strip()
                    product.properties = properties_dict
                except Exception:
                    product.properties = {}
        product.save()


def convert_categories_to_list(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.all():
        if not product.categories_deprecated or product.categories_deprecated == "[]":
            product.categories = []
        else:
            try:
                product.categories = [category.strip() for category in product.categories_deprecated.split(",")]
            except Exception:
                product.categories = []
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_alter_product_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="categories_deprecated",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="properties",
            new_name="properties_deprecated",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of tags for the product",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="properties",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.RunPython(code=convert_properties_to_json, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=convert_categories_to_list, reverse_code=migrations.RunPython.noop),
    ]
