# Generated by Django 5.2.4 on 2025-11-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_product_categories_temp_product_properties_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories_deprecated",
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="properties_deprecated",
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
