# Generated by Django 5.1.1 on 2024-10-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_conversation_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='dimensions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.embeddingdimension'),
        ),
    ]
