# Generated by Django 5.1.1 on 2024-11-22 14:23

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_dataset_owner_delete_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentembedding',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='model',
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk', to='catalog.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField()),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='catalog.documentchunk')),
                ('dimensions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.embeddingdimension')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.embeddingmodel')),
            ],
            options={
                'db_table_comment': "Embedding vectors collected for one chunk. One chunk may have several different embedding vectors which have different dimensions. Agent processing user's questions chooses the best vector for the purpose.",
            },
        ),
    ]
