# Generated by Django 5.1.1 on 2024-12-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_update_django_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='documentchunkembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='catalog.documentchunk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='product',
            name='entry_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
