# Generated by Django 5.1.1 on 2024-12-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_conversation_dimensions_and_more'),
        ('catalog', '0025_alter_document_data_set_alter_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunkembedding',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='documentchunkembedding',
            name='model',
        ),
        migrations.AddField(
            model_name='dataset',
            name='embedding_chunk_overlap',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='dataset',
            name='embedding_chunk_size',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='dataset',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-large', max_length=255),
        ),
        migrations.AddField(
            model_name='dataset',
            name='embedding_provider',
            field=models.CharField(default='OpenAI', max_length=255),
        ),
        migrations.AddField(
            model_name='dataset',
            name='embedding_vector_dimensions',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.document'),
        ),
        migrations.AddConstraint(
            model_name='documentchunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk',), name='document_chunk_embedding_uk'),
        ),
        migrations.DeleteModel(
            name='EmbeddingDimension',
        ),
        migrations.DeleteModel(
            name='EmbeddingModel',
        ),
    ]
