# Generated by Django 5.1.1 on 2024-12-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_documentchunkembedding_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField()),
                ('config', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField()),
                ('config', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documentsource',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_sources', to='catalog.dataset'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sources', to='catalog.dataset'),
        ),
    ]
