# Generated by Django 5.1.1 on 2024-12-12 14:08

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def move_embeddings(apps, schema_editor):
    embeddings = apps.get_model('catalog', 'DocumentChunkEmbedding')
    for embedding in embeddings.objects.all():
        # Move embedding from child table to the parent table.
        embedding.chunk.embedding = embedding.embedding
        embedding.chunk.save()


def reverse_move_embeddings(apps, schema_editor):
    # To make migration reversible we register a function, but there is nothing to do here
    # since on migrating back the newly added field will be dropped.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_delete_answerdocument'),
        ('catalog', '0027_documentsource_productsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(null=True),
        ),
        migrations.AlterField(
            model_name='documentchunkembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='catalog.documentchunk'),
        ),
        # Move embeddings from child to the parent table.
        migrations.RunPython(move_embeddings, reverse_move_embeddings),
        # Remove child table.
        migrations.DeleteModel(
            name='DocumentChunkEmbedding',
        ),
    ]
