# Generated by Django 5.1.1 on 2024-09-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasets',
            name='categories',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawdatasets',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rawdatasets',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawdatasets',
            name='properties',
            field=models.CharField(max_length=1024),
        ),
    ]
