# Generated by Django 5.1.1 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_answerdocument_document_embedding_and_more'),
        ('ecl', '0020_remove_documentembedding_dimensions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentEmbedding',
        ),
        migrations.AddConstraint(
            model_name='documentchunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'model', 'dimensions'), name='document_chunk_embedding_uk'),
        ),
    ]
