# Generated by Django 5.2.4 on 2025-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_is_service_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_limited_admin",
            field=models.BooleanField(default=False),
        ),
    ]
