# Generated by Django 5.1.1 on 2024-09-30 18:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0003_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContentEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_length', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecl.companies')),
                ('model_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecl.embeddingmodels')),
            ],
        ),
    ]
