# Generated by Django 5.1.1 on 2024-10-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0005_rename_content_id_contentembeddings_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentembeddings',
            old_name='vector_length',
            new_name='dimensions',
        ),
        migrations.AlterField(
            model_name='contentembeddings',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings', to='ecl.contents'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='ecl.companies'),
        ),
    ]
