# Generated by Django 5.1.1 on 2024-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0006_rename_vector_length_contentembeddings_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='embeddingmodels',
            name='code',
            field=models.CharField(default='UNSET', max_length=5),
        ),
    ]
