# Generated by Django 5.1.1 on 2024-10-04 08:59

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0008_alter_contents_title_alter_rawdatasets_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbeddingDimensions',
            new_name='EmbeddingDimension',
        ),
        migrations.RenameModel(
            old_name='RawDataSets',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Companies',
            new_name='DataSet',
        ),
        migrations.RenameModel(
            old_name='Contents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='ContentEmbeddings',
            new_name='DocumentEmbedding',
        ),
        migrations.RenameModel(
            old_name='EmbeddingModels',
            new_name='EmbeddingModel',
        ),
    ]
