# Generated by Django 5.1.1 on 2024-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0012_alter_conversation_model_answerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt_message',
            field=models.TextField(default=None, null=True),
        ),
    ]
