# Generated by Django 5.1.1 on 2024-10-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0014_owner_alter_conversation_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='answerdocument',
            table_comment='Document considered by our similarity search engine as relevant to the question. Documents from this table are used to formulate the answer.',
        ),
        migrations.AlterModelTableComment(
            name='documentembedding',
            table_comment="Embedding vectors collected for one document. One document may have several different embedding vectors which have different dimensions. Agent processing user's questions chooses the best vector for the purpose.",
        ),
        migrations.AlterModelTableComment(
            name='embeddingdimension',
            table_comment="Lengths of embedding vector that are collected from OpenAI for documents or products. For one item we may collect multiple embedding vectors of different lengths. Note: vectors for all dimensions from this table will be collected when action 'reload all embeddings' is performed by admin.",
        ),
        migrations.AlterModelTableComment(
            name='owner',
            table_comment='Owner groups data sets, for instance: all data sets that belong to one company.',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='system_name',
            field=models.CharField(default='system', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_name',
            field=models.CharField(default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='embeddingdimension',
            name='dimension',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='ecl.conversation'),
        ),
    ]
