# Generated by Django 5.1.1 on 2024-10-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0015_alter_answerdocument_table_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='question',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='AnswerDocument',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
