# Generated by Django 5.1.5 on 2025-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_remove_conversation_system_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
