# Generated by Django 5.1.1 on 2024-11-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_conversation_user_name_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt_message',
            field=models.TextField(null=True),
        ),
    ]
