# Generated by Django 5.1.1 on 2024-11-20 09:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_question(apps, schema_editor):
    Conversation = apps.get_model('agent', 'Conversation')
    Question = apps.get_model('agent', 'Question')
    Message = apps.get_model('agent', 'Message')
    for conversation in Conversation.objects.all():
        for question in Question.objects.filter(conversation=conversation).order_by('id'):
            # Create a question message.
            Message.objects.create(conversation=conversation,
                                   created_at=question.asked_at,
                                   role='user',
                                   text=question.question,
                                   rating=question.answer_rating,
                                   feedback=question.answer_feedback)
            # Create an answer message (if there was any).
            if question.answer:
                Message.objects.create(conversation=conversation,
                                       created_at=question.asked_at,
                                       role='agent',
                                       text=question.answer)

# Added to make this script reversible.
# We do not have to delete anything - the whole object will be dropped.
def reverse_migrate_question(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_question_answer_feedback_question_answer_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='agent.conversation')),
            ],
            options={
                'db_table_comment': "A message sent during a conversation. Role describes category of a message, it may be a question asked by a user, agent's answer, or system message.",
            },
        ),
        migrations.RunPython(migrate_question, reverse_migrate_question),
    ]
