# Generated by Django 5.2.4 on 2025-07-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_message_answer_failed"),
        ("catalog", "0007_rename_productchunk_productcontentchunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("config", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.dataset")),
            ],
        ),
    ]
