# Generated by Django 5.1.1 on 2024-12-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_answerdocument_document_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='model',
        ),
    ]
