# Generated by Django 5.1.1 on 2024-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_conversation_dimensions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerDocument',
        ),
    ]
