# Generated by Django 5.2.4 on 2025-09-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0016_conversationfile_llm_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationfile",
            name="file_category",
            field=models.CharField(choices=[("image", "Image"), ("file", "File")], default="file", max_length=32),
            preserve_default=False,
        ),
    ]
