# Generated by Django 5.2.4 on 2025-09-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0018_message_is_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_file",
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.conversationfile"
            ),
        ),
    ]
