# Generated by Django 5.2.4 on 2025-09-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0019_remove_message_is_file_message_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
