# Generated by Django 5.2.4 on 2025-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0024_alter_agent_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="widget_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("function", "Function"),
                    ("human", "Human"),
                    ("ai", "Ai"),
                    ("system", "System"),
                    ("intermediate_step", "Intermediate Step"),
                    ("file", "File"),
                    ("widget", "Widget"),
                ],
                max_length=50,
            ),
        ),
    ]
