# Generated by Django 5.2.12 on 2026-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0025_migrate_re_act_to_tool_calling'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
