# Generated by Django 5.2.12 on 2026-04-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_fix_unique_agent_name_constraint_exclude_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_summarized_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent.message'),
        ),
    ]
