# Generated by Django 5.1.1 on 2024-11-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_message'),
        ('ecl', '0020_remove_documentembedding_dimensions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdocument',
            name='document_embedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_document', to='ecl.documentchunkembedding'),
        )
    ]
