name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., 1.0.0)'
        required: true
        type: string
      push_latest:
        description: 'Also tag as latest'
        required: true
        default: true
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: upsidelab/enthusiast-server:${{ inputs.tag }}${{ inputs.push_latest && ',upsidelab/enthusiast-server:latest' || '' }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            upsidelab/enthusiast-frontend:${{ inputs.tag }}${{ inputs.push_latest && ',upsidelab/enthusiast-frontend:latest' || '' }}

